docs: make usage of Schema Object consistent
asyncapi/bindings pull request #143
Opened 2022-08-18 12:26 UTC by char0n

**Description**

[Main specification document](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md) says this:

![image](https://user-images.githubusercontent.com/193286/184107493-f9b132a3-bcf0-408f-8b56-41e0eacac2f2.png)

All the Schema Objects in main specification document has following type notation:

![image](https://user-images.githubusercontent.com/193286/184107641-b47240b3-bfb2-43cb-922c-6f5bd835165a.png)

All binding objects specification documents contain following type notation:

![image](https://user-images.githubusercontent.com/193286/184107838-a6245538-73b8-4694-99ce-d875fd5b6583.png)

---

From this, it is apparent that type notation for fields using `Schema Object`, is not consistent within the spec and probably needs to be clarified. There is no reason (at least none that I can see currently) why to constrain binding objects fields to using `Schema Object` and not allow `Reference Object` in it's place as well. The AsynAPI specification tells us following: `Alternatively, any time a Schema Object can be used, a Reference Object can be used in its place.` - this can also be interpreted that using `Reference Object` in binding objects fields is allowed, but if we check the [schemas](https://github.com/asyncapi/bindings/blob/master/http/json_schemas/message.json#L15), they tell us `Reference Object` is not allowed. As we already [stipulated before](https://github.com/asyncapi/spec/pull/781), the specification is the source of truth and not the schemas.

This PR open possibility to use `Reference Object` in binding objects fields and updates schemas to use latest versions of AsyncAPI  schemas (2.4.0). This also enhanced re-usability aspect of the spec. 

**Related issue(s)**

https://github.com/swagger-api/apidom/issues/1832

2022-08-25 05:07 UTC, fmvilas requested changes

2022-08-25 05:07 UTC, fmvilas commented on kafka/README.md
> +<a name="messageBindingObjectKey"></a>`key` | [Schema Object][schemaObject] \| [Reference Object](referenceObject) \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) | The messag
I think we can remove this now then:

```suggestion
<a name="messageBindingObjectKey"></a>`key` | [Schema Object][schemaObject] \| [Reference Object](referenceObject) \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) | The message key.
```

2022-08-25 10:35 UTC, char0n commented on kafka/README.md
> +<a name="messageBindingObjectKey"></a>`key` | [Schema Object][schemaObject] \| [Reference Object](referenceObject) \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) | The messag
Suggestion merged. Thanks!

2022-09-06 11:18 UTC, fmvilas submitted a review, later dismissed
LGTM 👍

2022-09-06 22:44 UTC, dalelane approved these changes

2022-09-09 16:54 UTC, char0n commented
@lbroudoux @GeraldLoeffler @derberg @KhudaDad414 would you be able to look at this PR please? THanks!

2022-09-12 19:19 UTC, derberg submitted a review, later dismissed

2022-09-19 17:32 UTC, smoya submitted a review, later dismissed

2022-09-20 12:11 UTC, char0n commented
@KhudaDad414 @lbroudoux @GeraldLoeffler pinging again on this one.

2022-09-20 14:06 UTC, lbroudoux submitted a review, later dismissed
Looks good to me and makes a lot of sense

2022-09-27 07:27 UTC, KhudaDad414 approved these changes
LGTM!

2022-09-28 16:38 UTC, GeraldLoeffler approved these changes
excellent - thank you!

2022-09-30 10:50 UTC, char0n commented
merged the changes from master, so unfortunately new round of reviews is required.

2022-09-30 10:53 UTC, KhudaDad414 approved these changes
LGTM!

2022-10-06 20:12 UTC, fmvilas submitted a review, later dismissed

2022-10-09 21:15 UTC, dalelane submitted a review, later dismissed

2022-10-10 18:00 UTC, derberg approved these changes

2022-11-06 01:15 UTC, jonaslagoni commented
Any reason this is not merged? 😆

2022-12-19 14:48 UTC, char0n commented
@jonaslagoni I guess only because of my inability to resolve the conflict in this PR for last 2 months ;]

2022-12-19 15:00 UTC, KhudaDad414 approved these changes

2022-12-23 04:20 UTC, fmvilas approved these changes
@derberg @dalelane please approve again 🙏

2023-01-02 16:51 UTC, dalelane approved these changes

2023-01-16 12:03 UTC, derberg approved these changes

2023-01-16 12:04 UTC, derberg commented
as multiple  bindings were modified we need below folks to approve again:
- @smoya 
- @lbroudoux 
- @GeraldLoeffler

2023-02-05 21:05 UTC, char0n commented
Haha this PR proved to be pretty difficult to merge ;]

2023-02-06 14:38 UTC, derberg commented
@smoya
@lbroudoux
@GeraldLoeffler

can you folks have a look 🙏🏼

2023-02-08 15:25 UTC, char0n commented
3 more needed ;]

2023-02-08 18:36 UTC, GeraldLoeffler approved these changes

2023-03-09 12:57 UTC, lbroudoux approved these changes
LGTM. Thanks!

2023-11-02 05:59 UTC, char0n commented
/rtm

2023-11-02 05:59 UTC, merged

2023-11-02 06:00 UTC, char0n commented
Thank you everybody for your patience. Finally merged!

2023-11-07 08:46 UTC, Tenischev commented
@char0n @derberg @fmvilas 
this looks strange
![image](https://github.com/asyncapi/bindings/assets/4137916/4151636a-2294-4b7a-b19c-7f52f13c6a73)

2023-11-07 09:17 UTC, smoya commented
> @char0n @derberg @fmvilas this looks strange ![image](https://user-images.githubusercontent.com/4137916/280974369-4151636a-2294-4b7a-b19c-7f52f13c6a73.png)

Indeed got merged with the Git merge HEAD marks left. See https://github.com/asyncapi/bindings/pull/143/files#diff-ba2c28c470746625d05c982e58e3b6fdd081ddae606d2918856189bb787c8b4fR148

@char0n are you ok fixing this? Otherwise I'm happy to do it so we do not leave that broken for so much time.

2023-11-07 12:53 UTC, derberg commented
isn't it the same as https://github.com/asyncapi/bindings/pull/219 ?

2023-11-10 10:50 UTC, char0n commented
@derberg yes, #219 and #220 are the same. Author of #219 closed it as he probably saw #220.