Update kafka bindings to v0.3.0 with support for scalar parameter values
asyncapi/bindings pull request #150
Opened 2022-09-26 22:00 UTC by vearutop

**Description**

Based on [slack discussion](https://asyncapi.slack.com/archives/C34F2JV0U/p1663919937776929) this PR extends `kafka`  bindings to allow scalar values to optimize for a common case when key/clientId/groupId can be defined as constant.

2022-09-27 07:42 UTC, fmvilas requested changes
Left some comments. Some of the suggestions are not related to your modifications but I thought we could take the opportunity now.

Also, I'm missing that you bump the version of the document at the top. We don't have any automation there yet for bindings so you have to change it manually.

2022-09-27 07:42 UTC, fmvilas commented on kafka/README.md
> +<a name="operationBindingObjectClientId"></a>`clientId` | [Schema Object][schemaObject] \| string | Id of the consumer inside a consumer group.
```suggestion
<a name="operationBindingObjectGroupId"></a>`groupId` | string \| [Schema Object][schemaObject] | Id of the consumer group or a [Schema Object][schemaObject] that validates it.
<a name="operationBindingObjectClientId"></a>`clientId` | [string \| [Schema Object][schemaObject] | Id of the consumer inside a consumer group or a [Schema Object][schemaObject] that validates it.
```

2022-09-27 07:42 UTC, fmvilas commented on kafka/README.md
> +<a name="messageBindingObjectKey"></a>`key` | [Schema Object][schemaObject] \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) \| string | The message key. **NOTE**: You can also
```suggestion
<a name="messageBindingObjectKey"></a>`key` | string \| [Schema Object][schemaObject] \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) | The message key or an object that validates the key. **NOTE**: You can also use a [Reference Object](https://asyncapi.io/docs/specifications/v2.1.0#referenceObject).
```

2022-09-27 08:00 UTC, fmvilas submitted a review, later dismissed
LGTM 👍 

Let's wait for @derberg, @lbroudoux, @KhudaDad414, and @dalelane reviews.

2022-09-27 08:06 UTC, derberg commented
as @lbroudoux and @dalelane are codeowners for kafka binding and @KhudaDad414 maintains JSON Schemas, I will not do the review here - already enough 👀 here 😃

2022-09-27 08:10 UTC, fmvilas commented
Oh yeah, forgot that Khuda maintains the schemas.

2022-09-27 08:30 UTC, KhudaDad414 requested changes
LGTM! just a little typo.

2022-09-27 08:30 UTC, KhudaDad414 commented on kafka/README.md
> +<a name="operationBindingObjectClientId"></a>`clientId` | [string \| [Schema Object][schemaObject] | Id of the consumer inside a consumer group or a [Schema Object][schemaObject] that validates it.
```suggestion
<a name="operationBindingObjectClientId"></a>`clientId` | string \| [Schema Object][schemaObject] | Id of the consumer inside a consumer group or a [Schema Object][schemaObject] that validates it.
```

2022-09-27 08:30 UTC, KhudaDad414 approved these changes

2022-09-27 13:01 UTC, dalelane commented on kafka/README.md
> +<a name="messageBindingObjectKey"></a>`key` | string \| [Schema Object][schemaObject] \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) | The message key or an object that valid
```suggestion
<a name="messageBindingObjectKey"></a>`key` | string \| [Schema Object][schemaObject] \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) | The message key or an object that validates the key. **NOTE**: You can also use a [Reference Object](https://asyncapi.io/docs/specifications/v2.4.0#referenceObject).
```

worth updating this while we're here?

2022-09-27 13:02 UTC, dalelane approved these changes
looks good - I think this will be helpful, thanks! 👍

2022-09-28 16:00 UTC, lbroudoux requested changes
LGTM. Just update schema references in `message.json` and we're good to go.

2022-09-28 16:00 UTC, lbroudoux commented on kafka/README.md
> +<a name="messageBindingObjectKey"></a>`key` | string \| [Schema Object][schemaObject] \| [AVRO Schema Object](https://avro.apache.org/docs/current/spec.html) | The message key or an object that valid
+1 for @dalelane suggestion

2022-09-28 16:00 UTC, lbroudoux commented on kafka/json_schemas/message.json
> +          "$ref": "https://raw.githubusercontent.com/asyncapi/asyncapi-node/v2.7.7/schemas/2.0.0.json#/definitions/schema"
Should be updated to `https://raw.githubusercontent.com/asyncapi/asyncapi-node/v2.14.0/schemas/2.4.0.json#/definitions/schema`

2022-10-07 08:24 UTC, vearutop commented
Oh, sorry for delay, I see these bindings were recently versioned with 0.3.0 for other changes, should I bump version to 0.3.1 (or to 0.4.0) here?

2022-10-07 08:49 UTC, fmvilas commented
@vearutop Yeah, bump it to 0.4.0 as it's actually a new "feature".

2022-10-09 21:16 UTC, dalelane submitted a review, later dismissed

2022-10-10 15:57 UTC, fmvilas approved these changes
LGTM 👍

2022-10-12 17:11 UTC, derberg commented
sorry folks, I wrote I won't review, but actually, today during 3.0 spec meeting it popped up and I read the thread on slack because of it.

can you help me understand why it is better to allow just plain string instead of following schema object:
```
          groupId:
            const: my-group
```

isn't it only a problem of bad example that suggest `enum` while better to have `const`?

2022-10-12 18:46 UTC, vearutop commented
Good thing about scalar value is that it has clear intent and is hard to misuse. When I first saw that `groupId` accepts schema I was genuinely confused (by that time I haven't checked examples yet). 

So in my opinion schema covers advanced cases where user would have to look in the docs anyway, while "string" simplifies basic case (constant value). It also works a bit like documentation, suggesting the type of value (schema does not limit itself in any way and lends itself for misuse if user is not careful about what goes into schema).

2022-10-14 10:18 UTC, fmvilas commented
Yeah, also a plain string is always a scalar value. A Schema may not be possible to convert down to a scalar value if it doesn't have `const` or an `enum` with a single element array. They serve two different purposes. A producer may want to know which exact value to send. A consumer may want to know how to validate it.

For instance, a publisher may send `key` as `user.signedupV1` and another publisher may set it to `user.signedupV2` but a potential consumer may just want to check that the value is either `user.signedupV1` or `user.signedupV2`, or that it simply matches a specific regex pattern.

The publishers want to have the scalar value they send. The consumer wants to have a Schema object that validates it. Does it make sense?

2022-10-17 21:04 UTC, dalelane commented
@lbroudoux do you think that covers everything you saw?

2022-10-18 09:34 UTC, derberg commented
yeah, I still think better is:

```yaml
groupId:
    const: my-group
    description: You can always specify more details for the user if you want
```

than:
```yaml
groupId: my-group
```

anyway, I suggest you provide an example for string and probably adjust example with single element `enum` to `const`

2022-10-18 15:31 UTC, lbroudoux commented
Still looking good to me. 👍 

Also I think it could be nice to illustrate both cases through different examples like:


```yaml
channels:
  test:
    publish:
      message:
        bindings:
          kafka:
            key: 'user.signedupV1'
```

OR

```yaml
channels:
  test:
    publish:
      message:
        bindings:
          kafka:
            key:
              type: string
              enum: ['user.signedupV1', 'user.signedupV2']
```

IMO this clearly illustrates that you can use this notation shortcut for self-explanatory values but have to switch to schema notation once you handle more complex cases.  In that later cases, additional `description` can make sense to explain the range of possible values.

2022-10-18 15:32 UTC, lbroudoux approved these changes

2022-11-22 22:16 UTC, vearutop commented
Hi, is there anything I can do to improve this PR?

2022-11-28 05:06 UTC, fmvilas commented
@vearutop Yeah, I think it's just a matter of adding examples as @derberg and @lbroudoux suggested.

2023-11-26 00:13 UTC, closed without merging