feat: add HTTP status code
asyncapi/bindings pull request #235
Opened 2024-01-11 22:25 UTC by jonaslagoni

**Description**
This PR adds the `status-code` property to the message object.

The reason for adding it to the message object and not the operation object, is that it feels more 
```
...
channels:
  HttpCustomersChannel:
    address: /customers
    messages:
      HttpCustomersGetMessageResponse:
        description: OK
        payload:
          $ref: '#/components/schemas/CustomerPaginated'
        bindings:
          http:
            status-code: 200
            bindingVersion: '0.3.0'

      HttpCustomersGetMessageResponse:
        description: Server error, could not complete request
        payload:
          $ref: '#/components/schemas/SomeError'
        bindings:
          http:
            status-code: 500
            bindingVersion: '0.3.0'

operations:
  GetCustomers:
    action: send
    channel:
       $ref: #/channels/HttpCustomersChannel
    bindings:
      http:
        method: GET
        bindingVersion: '0.3.0'
```

**Related issue(s)**
Fixes https://github.com/asyncapi/bindings/issues/234

2024-01-12 08:59 UTC, smoya commented
I understand the status code can't exist in the operation since in one channel can coexist several messages (responses) with a different status code each (200, 202, 500...). You won't be able to do this within a single operation.

2024-01-12 09:05 UTC, smoya submitted a review, later dismissed
LGTM! 🚀🌔

2024-01-12 09:07 UTC, smoya commented
Wondering how this will work with Operation Reply objects 🤔

2024-01-12 12:05 UTC, fmvilas requested changes

2024-01-12 12:05 UTC, fmvilas commented on http/README.md
> +<a name="messageBindingObjectStatusCode"></a>`status-code` | number | The HTTP response status code according to [RFC 9110](https://httpwg.org/specs/rfc9110.html#overview.of.status.codes).
We're using camel case everywhere else:

```suggestion
<a name="messageBindingObjectStatusCode"></a>`statusCode` | number | The HTTP response status code according to [RFC 9110](https://httpwg.org/specs/rfc9110.html#overview.of.status.codes).
```

2024-01-13 01:29 UTC, jonaslagoni commented on http/README.md
> +<a name="messageBindingObjectStatusCode"></a>`status-code` | number | The HTTP response status code according to [RFC 9110](https://httpwg.org/specs/rfc9110.html#overview.of.status.codes).
Applied :+1:

2024-01-13 01:40 UTC, jonaslagoni commented
When you define your application as a REST server i.e. you receive a request where you respond with a reply that has specific status codes it looks like this:

```yaml
asyncapi: 3.0.0
info:
  title: REST server
  version: 0.0.1
defaultContentType: application/json
servers:
  HttpServer:
    host: 'http://localhost:8080/api'
    protocol: http
    security:
      - type: http
        scheme: basic
      - type: http
        scheme: bearer
        bearerFormat: JWT
channels:
  HttpCustomersChannel:
    address: /customers
    servers:
      - $ref: '#/servers/HttpServer'
    messages:
      HttpCustomersGetMessage:
        payload:
          type: 'null'
      HttpCustomersGetMessageResponse:
        description: OK
        payload:
          $ref: '#/components/schemas/CustomerPaginated'
        bindings:
          http:
            statusCode: 200
operations:
  onListCustomers:
    action: receive
    description: listCustomers
    channel:
      $ref: '#/channels/HttpCustomersChannel'
    messages:
      - $ref: '#/channels/HttpCustomersChannel/messages/HttpCustomersGetMessage'
    reply:
      channel:
        $ref: '#/channels/HttpCustomersChannel'
      messages:
        - $ref: >-
            #/channels/HttpCustomersChannel/messages/HttpCustomersGetMessageResponse
components:
  schemas:
    Customer:
      type: object
    CustomerPaginated:
      type: object
```

When you define your application as interacting with a REST server as a client where are the one sending the request, nothing changes for the messages nor the status code 🤔 
```yaml
asyncapi: 3.0.0
info:
  title: REST client
  version: 0.0.1
defaultContentType: application/json
servers:
  HttpServer:
    host: 'http://localhost:8080/api'
    protocol: http
    security:
      - type: http
        scheme: basic
      - type: http
        scheme: bearer
        bearerFormat: JWT
channels:
  HttpCustomersChannel:
    address: /customers
    servers:
      - $ref: '#/servers/HttpServer'
    messages:
      HttpCustomersGetMessage:
        payload:
          type: 'null'
      HttpCustomersGetMessageResponse:
        description: OK
        payload:
          $ref: '#/components/schemas/CustomerPaginated'
        bindings:
          http:
            statusCode: 200
operations:
  onListCustomers:
    action: send
    description: listCustomers
    channel:
      $ref: '#/channels/HttpCustomersChannel'
    messages:
      - $ref: '#/channels/HttpCustomersChannel/messages/HttpCustomersGetMessage'
    reply:
      channel:
        $ref: '#/channels/HttpCustomersChannel'
      messages:
        - $ref: >-
            #/channels/HttpCustomersChannel/messages/HttpCustomersGetMessageResponse
components:
  schemas:
    Customer:
      type: object
    CustomerPaginated:
      type: object
```

In short, it just means that messages referenced in the operation should NOT have statusCode defined, but messages defined in the reply section SHOULD 🤔 

How do you folks suggest we clarify the interaction here in a meaningful way 🤔 ?

2024-01-17 12:25 UTC, fmvilas commented
> In short, it just means that messages referenced in the operation should NOT have statusCode defined, but messages defined in the reply section SHOULD 🤔

I think we can say that statusCode in the operation messages (not reply) can simply be ignored. We only take it into account inside the `reply` section. How does that sound?

2024-01-17 21:35 UTC, jonaslagoni commented
@fmvilas added the following as description (feel free to reformat and change it as needed):

```
The HTTP response status code according to [RFC 9110](https://httpwg.org/specs/rfc9110.html#overview.of.status.codes). `statusCode` is only relevant for messages referenced by the [operation reply object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationReplyObject) as they define the status code for the response, in all other cases this can safely be ignored.
```

2024-01-19 10:00 UTC, fmvilas approved these changes

2024-01-19 20:04 UTC, jonaslagoni commented
@smoya anything from your side?

2024-01-20 00:07 UTC, smoya approved these changes
> > In short, it just means that messages referenced in the operation should NOT have statusCode defined, but messages defined in the reply section SHOULD 🤔
> 
> I think we can say that statusCode in the operation messages (not reply) can simply be ignored. We only take it into account inside the `reply` section. How does that sound?

I don't feel this is very user friendly but I can't find a better alternative considering the status code SHOULD be located in the Message Object because the reasons already mentioned.

So 👍 in my side.

2024-01-25 22:03 UTC, jonaslagoni commented
Added the JSON schema changes here: https://github.com/asyncapi/spec-json-schemas/pull/484

Feel free to merge in any order you see fit 🙂

2024-01-30 04:15 UTC, jonaslagoni commented
/rtm

2024-01-30 04:15 UTC, merged